/**
 * Settings Writer
 *
 * Writes configuration to .env file
 */

import * as fs from 'fs';
import * as path from 'path';
import type { EnvironmentVariables } from './SettingsSchema.js';
import { SETTINGS_METADATA, DEFAULT_SETTINGS } from './SettingsSchema.js';

/**
 * Generate .env file content from environment variables
 */
export function generateEnvFileContent(env: Partial<EnvironmentVariables>): string {
  const lines: string[] = [];

  // Header
  lines.push('# Nexus Cortex Configuration');
  lines.push('# Generated by Settings Configurator');
  lines.push('# Last updated: ' + new Date().toISOString());
  lines.push('');

  // Group settings by category — must include ALL categories from SettingsSchema
  const categories = [
    { name: 'api_keys', title: 'API KEYS' },
    { name: 'models', title: 'MODEL CONFIGURATION' },
    { name: 'system', title: 'SYSTEM SETTINGS' },
    { name: 'mentorship', title: 'REACTIVE MENTORSHIP' },
    { name: 'context', title: 'CONTEXT MANAGEMENT' },
    { name: 'session', title: 'SESSION CONFIGURATION' },
    { name: 'loop_control', title: 'LOOP CONTROL' },
    { name: 'server_side_tools', title: 'SERVER-SIDE TOOLS' },
    { name: 'model_router', title: 'MODEL ROUTER' },
    { name: 'agent_workspace', title: 'AGENT WORKSPACE' },
    { name: 'training', title: 'ENDTURN GATE / TRAINING SUBSTRATE' },
    { name: 'runtime', title: 'RUNTIME FLAGS' },
  ];

  const knownKeys = new Set<string>();

  for (const category of categories) {
    const settings = SETTINGS_METADATA.filter(s => s.category === category.name);
    if (settings.length === 0) continue;

    lines.push('# ============================================');
    lines.push(`# ${category.title}`);
    lines.push('# ============================================');
    lines.push('');

    for (const setting of settings) {
      // Add description as comment
      if (setting.description) {
        lines.push(`# ${setting.description}`);
      }

      // Add valid choices as comment
      if (setting.type === 'choice' && setting.choices) {
        lines.push(`# Options: ${setting.choices.join(', ')}`);
      }

      // Get value (use provided value, or default, or empty string)
      const value = env[setting.key] ?? (DEFAULT_SETTINGS[setting.key as keyof typeof DEFAULT_SETTINGS] || '');

      // Write the setting
      lines.push(`${setting.key}=${value}`);
      lines.push('');
      knownKeys.add(setting.key);
    }
  }

  // Preserve any env vars NOT in SETTINGS_METADATA (runtime-only vars like
  // CORTEX_MODE, CORTEX_RECORD_DECISIONS, WEB_TOOLS_MODEL, etc.).
  // Without this, regenerating the file silently drops them.
  const extraKeys = Object.keys(env).filter(k => !knownKeys.has(k) && env[k as keyof EnvironmentVariables] !== undefined && env[k as keyof EnvironmentVariables] !== '');
  if (extraKeys.length > 0) {
    lines.push('# ============================================');
    lines.push('# ADDITIONAL SETTINGS (not in schema — preserved from prior .env)');
    lines.push('# ============================================');
    lines.push('');
    for (const key of extraKeys) {
      lines.push(`${key}=${env[key as keyof EnvironmentVariables]}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Write .env file
 */
export function writeEnvFile(projectPath: string, env: Partial<EnvironmentVariables>): void {
  const envPath = path.join(projectPath, '.env');
  const content = generateEnvFileContent(env);

  try {
    fs.writeFileSync(envPath, content, 'utf-8');
    console.log(`[SettingsWriter] Configuration saved to ${envPath}`);
  } catch (error: any) {
    throw new Error(`Failed to write .env file: ${error.message}`);
  }
}

/**
 * Update specific settings in .env file
 *
 * Preserves existing settings and comments
 */
export function updateEnvFile(projectPath: string, updates: Partial<EnvironmentVariables>): void {
  const envPath = path.join(projectPath, '.env');

  // Read existing file if it exists
  let existingEnv: Partial<EnvironmentVariables> = {};

  if (fs.existsSync(envPath)) {
    try {
      const content = fs.readFileSync(envPath, 'utf-8');
      const lines = content.split('\n');

      for (const line of lines) {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match && match[2] !== undefined) {
          const key = match[1] as keyof EnvironmentVariables;
          let value = match[2].trim();

          // Remove quotes
          if ((value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
          }

          existingEnv[key] = value;
        }
      }
    } catch (error: any) {
      console.warn(`[SettingsWriter] Error reading existing .env: ${error.message}`);
    }
  }

  // Merge updates with existing
  const mergedEnv = { ...existingEnv, ...updates };

  // Write back
  writeEnvFile(projectPath, mergedEnv);
}

/**
 * Create default .env file if it doesn't exist
 */
export function createDefaultEnvFile(projectPath: string): void {
  const envPath = path.join(projectPath, '.env');

  if (fs.existsSync(envPath)) {
    console.log(`[SettingsWriter] .env file already exists at ${envPath}`);
    return;
  }

  console.log(`[SettingsWriter] Creating default .env file at ${envPath}`);
  writeEnvFile(projectPath, DEFAULT_SETTINGS);
}

/**
 * Backup .env file
 */
export function backupEnvFile(projectPath: string): string | null {
  const envPath = path.join(projectPath, '.env');

  if (!fs.existsSync(envPath)) {
    return null;
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = path.join(projectPath, `.env.backup-${timestamp}`);

  try {
    fs.copyFileSync(envPath, backupPath);
    console.log(`[SettingsWriter] Backup created: ${backupPath}`);
    return backupPath;
  } catch (error: any) {
    console.error(`[SettingsWriter] Failed to create backup: ${error.message}`);
    return null;
  }
}

/**
 * Settings Writer Class
 */
export class SettingsWriter {
  private projectPath: string;

  constructor(projectPath: string = process.cwd()) {
    this.projectPath = projectPath;
  }

  /**
   * Write full configuration
   */
  write(env: Partial<EnvironmentVariables>): void {
    writeEnvFile(this.projectPath, env);
  }

  /**
   * Update specific settings
   */
  update(updates: Partial<EnvironmentVariables>): void {
    updateEnvFile(this.projectPath, updates);
  }

  /**
   * Create default configuration
   */
  createDefault(): void {
    createDefaultEnvFile(this.projectPath);
  }

  /**
   * Backup current configuration
   */
  backup(): string | null {
    return backupEnvFile(this.projectPath);
  }

  /**
   * Set API key
   */
  setApiKey(provider: 'anthropic' | 'openai' | 'google' | 'xai' | 'deepseek', apiKey: string): void {
    const keyMap = {
      anthropic: 'ANTHROPIC_API_KEY',
      openai: 'OPENAI_API_KEY',
      google: 'GOOGLE_API_KEY',
      xai: 'XAI_API_KEY',
      deepseek: 'DEEPSEEK_API_KEY'
    };

    const key = keyMap[provider];
    this.update({ [key]: apiKey } as Partial<EnvironmentVariables>);
  }

  /**
   * Enable/disable mentorship
   */
  setMentorshipEnabled(enabled: boolean): void {
    this.update({
      MENTORSHIP_ENABLED: enabled ? 'true' : 'false'
    });
  }

  /**
   * Set mentorship configuration
   */
  setMentorshipConfig(config: {
    enabled?: boolean;
    triggerOnError?: boolean;
    errorThreshold?: 'low' | 'medium' | 'high';
    keywordsEnabled?: boolean;
    customKeywords?: string[];
    helperModel?: string;
  }): void {
    const updates: Partial<EnvironmentVariables> = {};

    if (config.enabled !== undefined) {
      updates.MENTORSHIP_ENABLED = config.enabled ? 'true' : 'false';
    }

    if (config.triggerOnError !== undefined) {
      updates.MENTORSHIP_TRIGGER_ON_ERROR = config.triggerOnError ? 'true' : 'false';
    }

    if (config.errorThreshold) {
      updates.MENTORSHIP_ERROR_THRESHOLD = config.errorThreshold;
    }

    if (config.keywordsEnabled !== undefined) {
      updates.MENTORSHIP_KEYWORDS_ENABLED = config.keywordsEnabled ? 'true' : 'false';
    }

    if (config.customKeywords) {
      updates.MENTORSHIP_CUSTOM_KEYWORDS = config.customKeywords.join(',');
    }

    if (config.helperModel) {
      updates.MENTORSHIP_HELPER_MODEL = config.helperModel;
    }

    this.update(updates);
  }

  /**
   * Set default model
   */
  setDefaultModel(modelId: string): void {
    this.update({ DEFAULT_MODEL_ID: modelId });
  }

  /**
   * Set helper model
   */
  setHelperModel(modelId: string): void {
    this.update({ HELPER_MODEL_ID: modelId });
  }

  /**
   * Enable/disable debug mode
   */
  setDebugMode(enabled: boolean): void {
    this.update({ DEBUG: enabled ? 'true' : 'false' });
  }
}
