// Tool definitions for Claude Code tools in OpenAI function format
// These map Claude's tools to a format that OpenAI and compatible providers understand

import { generateToolId } from '../utils/ids.js';

export interface ToolDefinition {
  claudeName: string;
  openAIFunction: {
    name: string;
    description: string;
    parameters: {
      type: string;
      properties: Record<string, any>;
      required?: string[];
    };
  };
}

// Define all Claude Code tools in OpenAI function format
export const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    claudeName: 'Read',
    openAIFunction: {
      name: 'Read',  // Use PascalCase for all providers
      description: `Read the contents of a file. Returns content with line numbers in "cat -n" format (line_number TAB content).

OUTPUT FORMAT: Lines prefixed with line numbers. Any lines longer than 2000 characters are truncated. By default reads up to 2000 lines from the beginning.

USAGE:
- ALWAYS Read before Edit to get exact content for string matching
- After each edit, re-read the file before making further edits
- Use offset/limit for large files (e.g., offset: 100, limit: 50 to read lines 100-149)
- Can read images (PNG, JPG) — content is presented visually
- Can read PDFs — use limit for large PDFs
- Can read Jupyter notebooks (.ipynb) — returns all cells with outputs
- Returns an error (not crash) if file doesn't exist

RESEARCH QUALITY:
- When answering questions about a file, read enough to find ALL relevant sections — related code is often spread across the ENTIRE file, not clustered in one range
- If a question asks "list all X in this file", read the full file or use Grep first to locate every instance — stopping at the first cluster of results causes false negatives
- For audit/inventory tasks, prefer reading the complete file over targeted offset/limit reads`,
      parameters: {
        type: 'object',
        properties: {
          file_path: {
            type: 'string',
            description: 'Path to the file to read (relative or absolute)'
          },
          limit: {
            type: 'number',
            description: 'Maximum number of lines to read'
          },
          offset: {
            type: 'number',
            description: 'Line number to start reading from'
          }
        },
        required: ['file_path']
      }
    }
  },
  {
    claudeName: 'Write',
    openAIFunction: {
      name: 'Write',  // Use PascalCase for all providers
      description: `Write content to a file. Creates the file if it doesn't exist, overwrites if it does. Parent directories are created automatically.

GUIDANCE:
- PREFER Edit for modifying existing files — Write replaces the entire file
- If the file already exists, you MUST Read it first to understand current content
- Only use Write for creating NEW files or when the entire file content needs replacing
- After writing, re-read the file before making edits to it`,
      parameters: {
        type: 'object',
        properties: {
          file_path: {
            type: 'string',
            description: 'Path to write (user may provide relative, convert to absolute internally)'
          },
          content: {
            type: 'string',
            description: 'The content to write to the file'
          }
        },
        required: ['file_path', 'content']
      }
    }
  },
  {
    claudeName: 'WriteBinary',
    openAIFunction: {
      name: 'WriteBinary',
      description: `Write base64-encoded binary data to a file. Use for images (PNG, JPEG, WebP), PDFs, and other binary formats.

WHEN TO USE:
- Saving screenshots or images captured during browsing
- Writing PDF files generated by html2pdf --base64 in the sandbox
- Saving any binary data received as base64 in tool results
- Creating image assets for HTML documents

INPUT:
- data: raw base64 string OR a data URI (data:image/png;base64,...)
- mime_type: optional — auto-detected from file extension if omitted

DO NOT use this for text files — use Write instead.`,
      parameters: {
        type: 'object',
        properties: {
          file_path: {
            type: 'string',
            description: 'Path to write (e.g., "images/screenshot.png", "/tmp/report.pdf"). Parent directories are created automatically.'
          },
          data: {
            type: 'string',
            description: 'Base64-encoded binary content. Accepts raw base64 or a data URI (data:image/png;base64,...).'
          },
          mime_type: {
            type: 'string',
            description: 'MIME type (e.g., "image/png", "application/pdf"). Auto-detected from file extension if omitted.'
          }
        },
        required: ['file_path', 'data']
      }
    }
  },
  {
    claudeName: 'SandboxTransfer',
    openAIFunction: {
      name: 'SandboxTransfer',
      description: `Run a command in a remote sandbox (via MCP) and save its stdout to a local file.
Bridges the gap between sandbox-generated artifacts (PDFs, images, data files) and the local filesystem.

WHEN TO USE:
- Generating a PDF in the sandbox and saving it locally: command="html2pdf report.html --base64 --no-header", encoding="base64"
- Downloading a file in the sandbox and transferring it: command="curl -sL url | base64 -w0", encoding="base64"
- Capturing text output from sandbox commands: command="cat /tmp/results.csv", encoding="utf8"

COMMON PATTERN — PDF generation pipeline:
1. Write HTML locally or in sandbox via run_command
2. SandboxTransfer({ command: "cd /tmp/report && html2pdf report.html --base64 --no-header --paper a4", local_path: "report.pdf" })
   → Generates the PDF in the sandbox, transfers it as base64, writes locally

REQUIRES: An MCP server with run_command tool (e.g., nexus-browser). Fails gracefully if MCP is not connected.

ENCODING:
- "base64" (default): Decodes stdout from base64 to binary. Use for PDFs, images, archives.
- "utf8": Writes stdout as-is. Use for CSV, JSON, text, HTML.`,
      parameters: {
        type: 'object',
        properties: {
          command: {
            type: 'string',
            description: 'Shell command to run in the sandbox. Its stdout is captured and written to local_path.'
          },
          local_path: {
            type: 'string',
            description: 'Local file path to write output to. Parent directories are created automatically.'
          },
          encoding: {
            type: 'string',
            enum: ['base64', 'utf8'],
            description: 'How to decode stdout: "base64" (default) for binary, "utf8" for text.'
          },
          mime_type: {
            type: 'string',
            description: 'MIME type of the output file. Auto-detected from extension if omitted.'
          },
          timeout: {
            type: 'number',
            description: 'Command timeout in milliseconds (default: 60000). Use 90000+ for PDF generation.'
          },
          server: {
            type: 'string',
            description: 'MCP server name (default: "nexus-browser"). Must expose a run_command tool.'
          }
        },
        required: ['command', 'local_path']
      }
    }
  },
  {
    claudeName: 'Edit',
    openAIFunction: {
      name: 'Edit',  // Use PascalCase for all providers
      description: `Edit a file by replacing text. Performs exact string matching and replacement.

CRITICAL RULES:
- ALWAYS Read the file first — edits on unread files are rejected
- old_string must match EXACTLY — copy directly from Read output, including all whitespace
- Preserve exact indentation (spaces vs tabs matter, especially in Python)
- If edit fails with "not found", Read the file again and use updated content
- After each edit, re-read the file before making further edits
- Use replace_all: true to rename variables or replace all occurrences

ERROR RECOVERY:
- "not found" → whitespace/indentation mismatch. Read the file again.
- "found N times" → provide more surrounding context to make old_string unique
- "must Read first" → call Read on the file before attempting to edit

PARALLEL EXECUTION WARNING:
- NEVER edit the same file in parallel operations
- NEVER edit multiple files in parallel (use sequential edits)
- Safe to parallel: Read multiple files, Grep searches
- Must be sequential: Read→Edit for each file`,
      parameters: {
        type: 'object',
        properties: {
          file_path: {
            type: 'string',
            description: 'Path to file (resolve relative to absolute as needed)'
          },
          old_string: {
            type: 'string',
            description: 'EXACT text to replace (must match perfectly including whitespace)'
          },
          new_string: {
            type: 'string',
            description: 'The text to replace it with'
          },
          replace_all: {
            type: 'boolean',
            description: 'Replace all occurrences'
          }
        },
        required: ['file_path', 'old_string', 'new_string']
      }
    }
  },
  {
    claudeName: 'Bash',
    openAIFunction: {
      name: 'Bash',  // Keep as Bash for auto-approval to work
      description: `Execute bash/shell commands. Working directory persists between calls. Default timeout: 120 seconds (configurable).

IMPORTANT: Do NOT use Bash for operations that have dedicated tools:
- To read files → use Read (NOT cat, head, tail, sed)
- To edit files → use Edit (NOT sed -i, awk, perl -pi)
- To write/create files → use Write (NOT echo >, cat <<EOF >, tee)
- To search file contents → use Grep (NOT grep, rg, ag)
- To find files by name → use Glob (NOT find, ls -R)
Reserve Bash for system commands: git, npm, docker, curl, builds, tests, process management.

USAGE:
- Chain commands with && for sequential execution
- cd commands persist within the current Bash call but not across other tools
- Validation: python3 -m py_compile (Python), node --check (JavaScript), tsc --noEmit (TypeScript)
- Use 'test -f' or 'ls' to verify files exist before operations

AUTO-APPROVED COMMANDS (no user confirmation needed):
- Validation: python3 -m py_compile, npx tsc --noEmit, node --check, bash -n
- Information: pwd, ls, echo, which, test -f, test -d
- Build/Test: npm run build, npm run test, ./test-runner.sh
- With timeout: timeout <seconds> <command>

PARALLEL EXECUTION GUIDELINES:
- Safe to parallel: ls, pwd, echo, test -f, validation commands
- UNSAFE to parallel: cd, mv, rm, cp (file operations that change state)
- UNSAFE to parallel: npm install, pip install (package managers)
- Sequential required: build→test→validate chains`,
      parameters: {
        type: 'object',
        properties: {
          command: {
            type: 'string',
            description: 'The bash command to execute. Can use relative paths in shell context.'
          },
          description: {
            type: 'string',
            description: 'Clear description of what this command does'
          },
          timeout: {
            type: 'number',
            description: 'Timeout in milliseconds (default: 120000)'
          },
          run_in_background: {
            type: 'boolean',
            description: 'Set to true to run this command in the background. Use BashOutput to read the output later.'
          },
          dangerouslyDisableSandbox: {
            type: 'boolean',
            description: 'Set this to true to dangerously disable sandbox mode and run commands without sandboxing.'
          }
        },
        required: ['command']
      }
    }
  },
  {
    claudeName: 'Grep',
    openAIFunction: {
      name: 'Grep',  // Use PascalCase for all providers
      description: `Search file contents using ripgrep regex. Returns matching files or content lines.

OUTPUT MODES:
- "files_with_matches" (default): Returns file paths containing matches. Use this first to find relevant files, then Read specific ones.
- "content": Returns matching lines with file:line format. Supports -A/-B/-C context lines and -n line numbers.
- "count": Returns match counts per file.

PATTERN SYNTAX: Uses ripgrep regex (not grep). Literal braces need escaping: use "interface\\{\\}" to find "interface{}".

SEARCH STRATEGY:
- Search BROADLY first, then narrow — start with a general pattern, review ALL matches, THEN drill into specific files
- Before concluding "X doesn't exist", try alternate names, partial matches, and search parent directories — test files are often named differently than source files
- Use "count" mode to gauge result volume before fetching content
- When searching for all instances of a pattern (e.g., "list all middleware"), review the FULL result set — don't stop at the first cluster
- VERIFY after Read: if you Read a file and listed items from it, Grep the SAME file for a generic pattern (e.g., "new.*Middleware") to verify you didn't miss isolated instances far from the main cluster. Concentrated code sections create false confidence that you found everything.

TIPS:
- Filter by file type with glob ("*.ts") or type ("ts", "py", "rust")
- Use head_limit to cap output (e.g., head_limit: 20 for first 20 results)
- Use -i for case-insensitive search
- Use multiline: true for patterns spanning multiple lines
- Defaults to current working directory if no path specified`,
      parameters: {
        type: 'object',
        properties: {
          pattern: {
            type: 'string',
            description: 'The regex pattern to search for'
          },
          path: {
            type: 'string',
            description: 'File or directory to search in'
          },
          glob: {
            type: 'string',
            description: 'Glob pattern to filter files'
          },
          output_mode: {
            type: 'string',
            enum: ['content', 'files_with_matches', 'count'],
            description: 'Output mode'
          },
          '-A': {
            type: 'number',
            description: 'Number of lines to show after each match (rg -A). Requires output_mode: "content"'
          },
          '-B': {
            type: 'number',
            description: 'Number of lines to show before each match (rg -B). Requires output_mode: "content"'
          },
          '-C': {
            type: 'number',
            description: 'Number of lines to show before and after each match (rg -C). Requires output_mode: "content"'
          },
          '-n': {
            type: 'boolean',
            description: 'Show line numbers in output (rg -n). Requires output_mode: "content"'
          },
          '-i': {
            type: 'boolean',
            description: 'Case insensitive search (rg -i)'
          },
          type: {
            type: 'string',
            description: 'File type to search (rg --type). Common types: js, py, rust, go, java, etc.'
          },
          head_limit: {
            type: 'number',
            description: 'Limit output to first N lines/entries, equivalent to "| head -N"'
          },
          offset: {
            type: 'number',
            description: 'Skip first N entries before applying head_limit (for pagination). Use with head_limit for paging through large result sets.'
          },
          multiline: {
            type: 'boolean',
            description: 'Enable multiline mode where . matches newlines and patterns can span lines (rg -U --multiline-dotall)'
          }
        },
        required: ['pattern']
      }
    }
  },
  // File operations like rename, copy, delete are done via Bash commands (mv, cp, rm)
  {
    claudeName: 'Glob',
    openAIFunction: {
      name: 'Glob',  // Use PascalCase for all providers
      description: `Find files by name pattern using glob matching. Returns file paths sorted by modification time (newest first).

PATTERN EXAMPLES:
- "**/*.ts" — all TypeScript files recursively
- "src/**/*.test.ts" — test files in src/
- "**/config.json" — config.json anywhere in tree
- "*.md" — markdown files in current directory only

SEARCH STRATEGY:
- Start with a broad pattern, then narrow — "**/*Middleware*" before "src/middleware/Retry*"
- When inventorying a category, use MULTIPLE patterns to catch naming variations (e.g., "*Middleware*" AND "*middleware*" AND "*Service*")
- Don't assume directory structure — use recursive "**/" patterns first

Use this instead of Bash "find" command. Faster and returns structured results.`,
      parameters: {
        type: 'object',
        properties: {
          pattern: {
            type: 'string',
            description: 'The glob pattern to match'
          },
          path: {
            type: 'string',
            description: 'Directory to search in'
          }
        },
        required: ['pattern']
      }
    }
  },
  {
    claudeName: 'WebSearch',
    openAIFunction: {
      name: 'WebSearch',  // Use PascalCase for all providers
      description: 'Search the web for current information. Returns search result snippets with URLs. Use for facts beyond training data, current events, documentation lookups, or API references.',
      parameters: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'The search query'
          },
          allowed_domains: {
            type: 'array',
            items: { type: 'string' },
            description: 'Only include results from these domains'
          },
          blocked_domains: {
            type: 'array',
            items: { type: 'string' },
            description: 'Never include results from these domains'
          }
        },
        required: ['query']
      }
    }
  },
  {
    claudeName: 'WebFetch',
    openAIFunction: {
      name: 'WebFetch',  // Use PascalCase for all providers
      description: `Fetch and analyze web content from a URL. Converts HTML to markdown, then processes with your prompt.

USAGE:
- Provide url and prompt as separate parameters
- The prompt describes what information to extract from the page
- HTTP URLs are auto-upgraded to HTTPS
- Results may be summarized if content is very large
- 15-minute cache for repeated requests to the same URL
- For GitHub URLs, prefer Bash with "gh" CLI instead (e.g., gh pr view, gh issue view)`,
      parameters: {
        type: 'object',
        properties: {
          url: {
            type: 'string',
            description: 'The URL to fetch content from (must start with http:// or https://)'
          },
          prompt: {
            type: 'string',
            description: 'What information to extract or analyze from the fetched page'
          }
        },
        required: ['url', 'prompt']
      }
    }
  },
  {
    claudeName: 'Task',
    openAIFunction: {
      name: 'Task',  // Use PascalCase for all providers
      description: `Launch autonomous sub-agents for complex, multi-step tasks. Each agent runs in its own process with its own tools and session.

PARALLEL EXECUTION: Multiple Task tool_use blocks in ONE response = parallel (4x faster). One per response = sequential.

WHEN TO USE: Complex research needing many searches, multi-step operations that can run independently, parallel analysis of different subsystems.
WHEN NOT TO USE: Simple file reads (use Read), quick searches (use Grep/Glob), operations needing immediate results.

AGENT TYPES (subagent_type):
- "explore" — Fast codebase search and file discovery. Use for finding files, tracing code, answering "where is X?"
- "plan" — Architecture analysis and implementation planning. Use for designing approaches before coding.
- "general-purpose" — Multi-step research and implementation. Use for complex tasks needing multiple tools.
- "code-reviewer" — Code quality, security, and style review.
- "test-writer" — Generate unit and integration tests.
- "doc-writer" — Create and update documentation.
- "refactor" — Safe code refactoring with verification.
- "context-research" — Deep research across files and history.

PROMPT TIPS: Include all context (file paths, patterns). Specify expected output format. Each agent is stateless — provide complete instructions.

PERMISSIONS: Read/Glob/Grep auto-approved. Write/Edit/Bash require user approval.`,
      parameters: {
        type: 'object',
        properties: {
          description: {
            type: 'string',
            description: 'Short (3-5 word) description of the task for UI display'
          },
          prompt: {
            type: 'string',
            description: 'Complete task instructions including all context, expected outputs, and any file paths needed. Sub-agents are stateless and need full context.'
          },
          subagent_type: {
            type: 'string',
            description: 'Agent type: "general-purpose" (complex tasks), "Explore" (fast searches), "Plan" (architecture)'
          }
        },
        required: ['description', 'prompt', 'subagent_type']
      }
    }
  },
  {
    claudeName: 'TodoCreate',
    openAIFunction: {
      name: 'TodoCreate',
      description: `Create a task for tracking multi-step work. Call once per task. All start as pending.

For each task you create, follow this lifecycle:
  TodoUpdate(taskId, status="in_progress") -> do the work -> TodoUpdate(taskId, status="completed")

WHEN TO USE: Tasks with 3+ steps. SKIP FOR: trivial single-step tasks.`,
      parameters: {
        type: 'object',
        properties: {
          content: {
            type: 'string',
            description: 'Brief task title in imperative form (e.g., "Fix authentication bug")'
          },
          description: {
            type: 'string',
            description: 'Detailed description of what needs to be done'
          },
          activeForm: {
            type: 'string',
            description: 'Present continuous form shown while in progress (e.g., "Fixing authentication bug")'
          }
        },
        required: ['content']
      }
    }
  },
  {
    claudeName: 'TodoUpdate',
    openAIFunction: {
      name: 'TodoUpdate',
      description: `Update task status or details by ID.

LIFECYCLE — follow for every task:
  TodoUpdate(taskId, status="in_progress")  <- before starting work
  TodoUpdate(taskId, status="completed")    <- after finishing work

Supports batch: pass comma-separated IDs (e.g., taskId="1,2,3") to update multiple tasks at once.
Task IDs are plain numbers (e.g., "1", "2"). Do not include "#".`,
      parameters: {
        type: 'object',
        properties: {
          taskId: {
            type: 'string',
            description: 'Task ID(s) to update. Single: "1". Batch: "1,2,3".'
          },
          status: {
            type: 'string',
            enum: ['pending', 'in_progress', 'completed'],
            description: 'New status for the task'
          },
          content: {
            type: 'string',
            description: 'New task title (optional)'
          },
          description: {
            type: 'string',
            description: 'New description (optional)'
          },
          activeForm: {
            type: 'string',
            description: 'New active form (optional)'
          }
        },
        required: ['taskId']
      }
    }
  },
  {
    claudeName: 'TodoList',
    openAIFunction: {
      name: 'TodoList',
      description: 'List all tasks with their current status. Use to check progress, find task IDs, or review what is pending.',
      parameters: {
        type: 'object',
        properties: {},
        required: []
      }
    }
  },
  {
    claudeName: 'NotebookEdit',
    openAIFunction: {
      name: 'NotebookEdit',  // Use PascalCase for all providers
      description: 'Edit Jupyter notebook cells',
      parameters: {
        type: 'object',
        properties: {
          notebook_path: {
            type: 'string',
            description: 'Path to the Jupyter notebook'
          },
          cell_id: {
            type: 'string',
            description: 'ID of the cell to edit'
          },
          cell_type: {
            type: 'string',
            enum: ['code', 'markdown'],
            description: 'Type of cell'
          },
          edit_mode: {
            type: 'string',
            enum: ['replace', 'insert', 'delete'],
            description: 'Edit operation type'
          },
          new_source: {
            type: 'string',
            description: 'New content for the cell'
          }
        },
        required: ['notebook_path', 'new_source']
      }
    }
  },
  {
    claudeName: 'ExitPlanMode',
    openAIFunction: {
      name: 'ExitPlanMode',  // Use PascalCase for all providers
      description: 'Exit planning mode and start implementation',
      parameters: {
        type: 'object',
        properties: {
          plan: {
            type: 'string',
            description: 'The plan to present to the user'
          }
        },
        required: ['plan']
      }
    }
  },
  {
    claudeName: 'BashOutput',
    openAIFunction: {
      name: 'BashOutput',  // Use PascalCase for all providers
      description: `Retrieve output from a running or completed background bash shell started with run_in_background: true.

- Returns only NEW output since your last check (incremental reads)
- Shows process status: Running or Exited with exit code
- Use repeatedly to poll a long-running command until it completes
- Use filter to search output with regex (e.g., filter: "ERROR|WARN")

WORKFLOW:
1. Start: Bash({ command: "npm test", run_in_background: true }) → returns bash_id
2. Poll: BashOutput({ bash_id }) → check status + read new output
3. Done: When status shows "Exited", all output has been captured
4. Cleanup: KillShell({ shell_id: bash_id }) if process hangs`,
      parameters: {
        type: 'object',
        properties: {
          bash_id: {
            type: 'string',
            description: 'The ID of the background shell (returned by Bash with run_in_background: true)'
          },
          filter: {
            type: 'string',
            description: 'Regex to filter output lines (e.g., "ERROR|FAIL" to show only errors)'
          }
        },
        required: ['bash_id']
      }
    }
  },
  {
    claudeName: 'KillShell',
    openAIFunction: {
      name: 'KillShell',  // Use PascalCase for all providers
      description: `Stop a running background bash shell by its ID. Use when a background process hangs, takes too long, or is no longer needed. The shell ID is the same bash_id returned by Bash with run_in_background: true.`,
      parameters: {
        type: 'object',
        properties: {
          shell_id: {
            type: 'string',
            description: 'The ID of the background shell to stop (same as bash_id from BashOutput)'
          }
        },
        required: ['shell_id']
      }
    }
  },
  // =====================================
  // HISTORICAL RETRIEVAL TOOLS - Week 3
  // =====================================

  {
    claudeName: 'SearchConversationHistory',
    openAIFunction: {
      name: 'SearchConversationHistory',
      description: `Search through conversation history including compacted boundaries.

This tool searches both recent messages and compacted summaries to find relevant content
from the entire conversation timeline.`,
      parameters: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'Search query string'
          },
          maxResults: {
            type: 'number',
            description: 'Maximum number of results to return',
            default: 10
          },
          timeRange: {
            type: 'object',
            properties: {
              start: { type: 'string', format: 'date-time' },
              end: { type: 'string', format: 'date-time' }
            },
            description: 'Optional time range filter'
          },
          includeCompacted: {
            type: 'boolean',
            description: 'Include compacted messages in search',
            default: true
          }
        },
        required: ['query']
      }
    }
  },

  {
    claudeName: 'GetConversationSegment',
    openAIFunction: {
      name: 'GetConversationSegment',
      description: `Retrieve a specific segment of conversation history at different detail levels.

Can retrieve by turn range or checkpoint ID in full, summary, or compressed format.`,
      parameters: {
        type: 'object',
        properties: {
          turnRange: {
            type: 'object',
            properties: {
              start: {
                type: 'number',
                description: 'Starting turn number (1-based)'
              },
              end: {
                type: 'number',
                description: 'Ending turn number (inclusive)'
              }
            },
            description: 'Turn range to retrieve'
          },
          checkpointId: {
            type: 'string',
            description: 'Checkpoint ID to retrieve from'
          },
          format: {
            type: 'string',
            enum: ['full', 'summary', 'compressed'],
            description: 'Format of the returned segment',
            default: 'summary'
          }
        }
      }
    }
  },

  {
    claudeName: 'ListCompactionBoundaries',
    openAIFunction: {
      name: 'ListCompactionBoundaries',
      description: `List all compaction boundaries (conversation summaries) with IDs.

Shows where conversation has been compacted with token savings and metadata.`,
      parameters: {
        type: 'object',
        properties: {
          includeMetadata: {
            type: 'boolean',
            description: 'Include detailed metadata in response',
            default: true
          }
        }
      }
    }
  },

  {
    claudeName: 'RequestHistoricalContext',
    openAIFunction: {
      name: 'RequestHistoricalContext',
      description: `Request historical context using cheap helper model. Cost-effective for accessing archived context.

Uses FREE Gemma models to generate context from historical conversation data.`,
      parameters: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'Query describing what historical context is needed'
          },
          detailLevel: {
            type: 'string',
            enum: ['brief', 'standard', 'detailed'],
            description: 'Detail level for the response',
            default: 'standard'
          },
          maxTokens: {
            type: 'number',
            description: 'Maximum tokens for the response',
            default: 1000
          },
          useHelperModel: {
            type: 'boolean',
            description: 'Whether to use helper model (vs main model)',
            default: true
          }
        },
        required: ['query']
      }
    }
  },

  {
    claudeName: 'CodeExecute',
    openAIFunction: {
      name: 'CodeExecute',
      description: `Execute JavaScript code for token-efficient tool chaining. Only console.log() output enters the context window.

Write code that calls multiple tools in sequence, processes results, and outputs only what matters. Reduces round-trips and token usage significantly.

Top-level await supported. Available globals: all registered tool functions (ReadFile, WriteFile, Shell, Glob, Grep, etc.).`,
      parameters: {
        type: 'object',
        properties: {
          code: {
            type: 'string',
            description: 'JavaScript code to execute. Use console.log() to output results.'
          },
          timeout: {
            type: 'number',
            description: 'Execution timeout in ms (default 5000, max 30000)'
          }
        },
        required: ['code']
      }
    }
  },

  {
    claudeName: 'SearchTools',
    openAIFunction: {
      name: 'SearchTools',
      description: `Search the tool registry to discover available tools by name, description, or category. Use when deferred tool loading is active and you need tools not in the current list.`,
      parameters: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'Search query to match tool names and descriptions'
          },
          category: {
            type: 'string',
            description: 'Filter by tool category (e.g., "execution", "search", "file")'
          }
        }
      }
    }
  }
];

// Convert Claude tool format to OpenAI function calling format
export function claudeToolToOpenAI(toolName: string, toolInput: any): any {
  const toolDef = TOOL_DEFINITIONS.find(t => t.claudeName === toolName);
  if (!toolDef) {
    console.warn(`Unknown tool: ${toolName}`);
    return null;
  }

  // Map Claude's parameter names to OpenAI function parameter names
  const paramMapping: Record<string, Record<string, string>> = {
    'Read': { 'file_path': 'file_path', 'limit': 'limit', 'offset': 'offset' },
    'Write': { 'file_path': 'file_path', 'content': 'content' },
    'Edit': { 'file_path': 'file_path', 'old_string': 'old_string', 'new_string': 'new_string', 'replace_all': 'replace_all' },
    'Bash': { 'command': 'command', 'description': 'description', 'timeout': 'timeout', 'run_in_background': 'run_in_background', 'dangerouslyDisableSandbox': 'dangerouslyDisableSandbox' },
    'Grep': { 'pattern': 'pattern', 'path': 'path', 'glob': 'glob', 'output_mode': 'output_mode', '-A': '-A', '-B': '-B', '-C': '-C', '-n': '-n', '-i': '-i', 'type': 'type', 'head_limit': 'head_limit', 'multiline': 'multiline' },
    // 'LS': removed - not a real Claude tool
    'Glob': { 'pattern': 'pattern', 'path': 'path' },
    'WebSearch': { 'query': 'query', 'allowed_domains': 'allowed_domains', 'blocked_domains': 'blocked_domains' },
    'WebFetch': { 'url': 'url', 'prompt': 'prompt' },
    'Task': { 'description': 'description', 'prompt': 'prompt', 'subagent_type': 'subagent_type' },
    'TodoCreate': { 'content': 'content', 'description': 'description', 'activeForm': 'activeForm' },
    'TodoUpdate': { 'taskId': 'taskId', 'status': 'status', 'content': 'content', 'description': 'description', 'activeForm': 'activeForm' },
    'TodoList': {},
    'NotebookEdit': { 'notebook_path': 'notebook_path', 'cell_id': 'cell_id', 'cell_type': 'cell_type', 'edit_mode': 'edit_mode', 'new_source': 'new_source' },
    'ExitPlanMode': { 'plan': 'plan' },
    'BashOutput': { 'bash_id': 'bash_id', 'filter': 'filter' },
    'KillShell': { 'shell_id': 'shell_id' },
    'CodeExecute': { 'code': 'code', 'timeout': 'timeout' },
    'SearchTools': { 'query': 'query', 'category': 'category' }
  };

  const mappedParams: Record<string, any> = {};
  const mapping = paramMapping[toolName] || {};
  
  for (const [claudeParam, openAIParam] of Object.entries(mapping)) {
    if (toolInput[claudeParam] !== undefined && toolInput[claudeParam] !== null) {
      // Skip empty arrays for domain filters
      if ((claudeParam === 'allowed_domains' || claudeParam === 'blocked_domains') && 
          Array.isArray(toolInput[claudeParam]) && 
          toolInput[claudeParam].length === 0) {
        continue;
      }
      mappedParams[openAIParam] = toolInput[claudeParam];
    }
  }

  return {
    name: toolDef.openAIFunction.name,
    arguments: JSON.stringify(mappedParams)
  };
}

// Convert OpenAI function call back to Claude tool format
export function openAIToolToClaude(functionName: string, functionArgs: string | object): any {
  const debugMode = process.env.DEBUG_PORTKEY === 'true';
  if (debugMode) {
    console.log(`[TOOL CONVERSION] openAIToolToClaude called with function: ${functionName}`);
  }
  let args;
  try {
    args = typeof functionArgs === 'string' ? JSON.parse(functionArgs) : functionArgs;
    if (debugMode) {
      console.log(`[TOOL CONVERSION] Parsed arguments:`, JSON.stringify(args, null, 2));
    }
  } catch (error) {
    if (process.env.DEBUG_PORTKEY === 'true') {
      console.error(`[TOOL CONVERSION] Failed to parse arguments for ${functionName}:`, functionArgs);
    }
    // Try to clean up common issues like line breaks in strings
    if (typeof functionArgs === 'string') {
      try {
        // Remove line breaks within string values
        const cleaned = functionArgs.replace(/(\n|\r)/g, ' ');
        args = JSON.parse(cleaned);
      } catch (cleanupError) {
        if (process.env.DEBUG_PORTKEY === 'true') {
          console.error(`[TOOL CONVERSION] Cleanup also failed:`, cleanupError);
        }
        return null;
      }
    } else {
      return null;
    }
  }
  
  // Reverse mapping from OpenAI function names to Claude tool names
  // Updated to match the actual names we send to OpenAI/Grok
  const reverseMapping: Record<string, string> = {
    // Direct mappings (names we actually use)
    'Bash': 'Bash',
    'Read': 'Read',
    'Write': 'Write',
    'Edit': 'Edit',
    'Grep': 'Grep',
    'Glob': 'Glob',
    'WebSearch': 'WebSearch',
    'WebFetch': 'WebFetch',
    'Task': 'Task',
    'TodoCreate': 'TodoCreate',
    'TodoUpdate': 'TodoUpdate',
    'TodoList': 'TodoList',
    'NotebookEdit': 'NotebookEdit',
    'ExitPlanMode': 'ExitPlanMode',
    'BashOutput': 'BashOutput',
    'KillShell': 'KillShell',
    // Legacy mappings (kept for compatibility)
    'read_file': 'Read',
    'write_file': 'Write',
    'edit_file': 'Edit',
    'run_command': 'Bash',
    'run_bash_command': 'Bash',
    'search_files': 'Grep',
    'list_directory': 'Bash',
    'find_files': 'Glob',
    'rename_file': 'Bash',
    'copy_file': 'Bash',
    'delete_file': 'Bash',
    'web_search': 'WebSearch',
    'web_fetch': 'WebFetch',
    'launch_agent': 'Task',
    'manage_todos': 'TodoCreate',  // Legacy mapping
    'todo_create': 'TodoCreate',
    'todo_update': 'TodoUpdate',
    'todo_list': 'TodoList',
    'notebook_edit': 'NotebookEdit',
    'exit_plan_mode': 'ExitPlanMode',  // Fixed: snake_case mapping
    'get_bash_output': 'BashOutput',
    'kill_shell': 'KillShell'
  };

  const claudeToolName = reverseMapping[functionName];
  if (!claudeToolName) {
    console.warn(`Unknown function: ${functionName}`);
    return null;
  }

  // Special handling for file operations - convert to bash commands
  if (functionName === 'rename_file') {
    const oldPath = args.old_path || args.src || args.source || args.from;
    const newPath = args.new_path || args.dst || args.destination || args.to;
    
    if (oldPath && newPath) {
      return {
        type: 'tool_use',
        id: generateToolId(),
        name: 'Bash',
        input: {
          command: `mv "${oldPath}" "${newPath}"`,
          description: `Rename ${oldPath} to ${newPath}`
        }
      };
    }
  }
  
  if (functionName === 'copy_file') {
    const source = args.source || args.src || args.from;
    const destination = args.destination || args.dst || args.to;
    const recursive = args.recursive || false;
    
    if (source && destination) {
      const cpFlags = recursive ? '-r' : '';
      return {
        type: 'tool_use',
        id: generateToolId(),
        name: 'Bash',
        input: {
          command: `cp ${cpFlags} "${source}" "${destination}"`.trim(),
          description: `Copy ${source} to ${destination}`
        }
      };
    }
  }
  
  if (functionName === 'delete_file') {
    const path = args.path || args.file || args.target;
    const recursive = args.recursive || false;
    
    if (path) {
      const rmFlags = recursive ? '-rf' : '-f';
      return {
        type: 'tool_use',
        id: generateToolId(),
        name: 'Bash',
        input: {
          command: `rm ${rmFlags} "${path}"`,
          description: `Delete ${path}`
        }
      };
    }
  }
  
  // Special handling for WebSearch - only include domains if specified
  if (functionName === 'web_search') {
    if (process.env.DEBUG_PORTKEY === 'true') {
      console.log('[WEBSEARCH DEBUG] Raw args received:', JSON.stringify(args, null, 2));
    }
    
    const searchParams: any = { query: args.query };
    
    // Only add domain filters if they actually have values
    // CRITICAL: Check for both existence AND non-empty arrays
    if (args.allowed_domains && Array.isArray(args.allowed_domains) && args.allowed_domains.length > 0) {
      if (process.env.DEBUG_PORTKEY === 'true') {
        console.log('[WEBSEARCH DEBUG] Adding allowed_domains:', args.allowed_domains);
      }
      searchParams.allowed_domains = args.allowed_domains;
    }
    
    // CRITICAL: Also check blocked_domains isn't an empty array
    if (args.blocked_domains && Array.isArray(args.blocked_domains) && args.blocked_domains.length > 0) {
      if (process.env.DEBUG_PORTKEY === 'true') {
        console.log('[WEBSEARCH DEBUG] Adding blocked_domains:', args.blocked_domains);
      }
      searchParams.blocked_domains = args.blocked_domains;
    }
    
    // Log if we're filtering out empty arrays
    if (args.blocked_domains && Array.isArray(args.blocked_domains) && args.blocked_domains.length === 0) {
      if (process.env.DEBUG_PORTKEY === 'true') {
        console.log('[WEBSEARCH DEBUG] Filtered out empty blocked_domains array');
      }
    }
    if (args.allowed_domains && Array.isArray(args.allowed_domains) && args.allowed_domains.length === 0) {
      if (process.env.DEBUG_PORTKEY === 'true') {
        console.log('[WEBSEARCH DEBUG] Filtered out empty allowed_domains array');
      }
    }
    
    if (process.env.DEBUG_PORTKEY === 'true') {
      console.log('[WEBSEARCH DEBUG] Final params being sent to Claude:', JSON.stringify(searchParams, null, 2));
    }
    
    return {
      type: 'tool_use',
      id: generateToolId(),
      name: 'WebSearch',
      input: searchParams
    };
  }
  
  // Special handling for WebFetch
  if (functionName === 'web_fetch') {
    if (process.env.DEBUG_PORTKEY === 'true') {
      console.log('[WEBFETCH DEBUG] Raw args received:', JSON.stringify(args, null, 2));
    }
    
    const fetchParams = {
      url: args.url,
      prompt: args.prompt || 'Summarize the content'
    };
    
    if (process.env.DEBUG_PORTKEY === 'true') {
      console.log('[WEBFETCH DEBUG] Final params being sent to Claude:', JSON.stringify(fetchParams, null, 2));
    }
    
    return {
      type: 'tool_use',
      id: generateToolId(),
      name: 'WebFetch',
      input: fetchParams
    };
  }
  
  // Handle common parameter name variations for standard tools
  if (functionName === 'write_file') {
    // Handle path vs file_path variation
    if (args.path && !args.file_path) {
      args.file_path = args.path;
      delete args.path;
    }
  }
  
  if (functionName === 'read_file') {
    // Handle path vs file_path variation
    if (args.path && !args.file_path) {
      args.file_path = args.path;
      delete args.path;
    }
  }
  
  if (functionName === 'edit_file') {
    // Handle path vs file_path variation
    if (args.path && !args.file_path) {
      args.file_path = args.path;
      delete args.path;
    }
  }
  
  if (functionName === 'list_directory') {
    // Convert list_directory to Bash ls command
    const path = args.path || args.directory || '.';
    const ignorePatterns = args.ignore || [];

    // Build ls command with appropriate flags
    let lsCommand = `ls -la "${path}"`;
    if (ignorePatterns.length > 0) {
      // Add grep filtering for ignore patterns if needed
      const grepFilters = ignorePatterns.map((p: string) => `grep -v "${p}"`).join(' | ');
      lsCommand = `${lsCommand} | ${grepFilters}`;
    }

    // Convert to Bash command format
    args = {
      command: lsCommand,
      description: `List directory contents: ${path}`
    };
  }

  return {
    type: 'tool_use',
    id: generateToolId(),
    name: claudeToolName,
    input: args
  };
}

// Get all tool definitions in OpenAI format for API calls
export function getAllOpenAITools() {
  return TOOL_DEFINITIONS.map(t => ({
    type: 'function',
    function: t.openAIFunction
  }));
}

// Get all tool definitions in Claude format
export function getAllClaudeTools() {
  return TOOL_DEFINITIONS.map(t => ({
    name: t.claudeName,
    description: t.openAIFunction.description,
    input_schema: t.openAIFunction.parameters
  }));
}